
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND ATOMIC DOUBLEIMPLY EXCLUSIVEOR IMPLY LEFTPARENTHESIS NEGATE OR RIGHTPARENTHESIS\n    mainStructure : molecular\n    \n    operator : OR\n    operator : AND\n    operator : IMPLY\n    operator : DOUBLEIMPLY\n    operator : EXCLUSIVEOR\n    \n    molecular : lparenthesis molecular rparenthesis\n    molecular : lparenthesis molecular operator molecular rparenthesis\n    molecular : lparenthesis molecular operator atomic rparenthesis\n    molecular : lparenthesis atomic operator atomic rparenthesis\n    molecular : molecular operator molecular\n    molecular : molecular operator atomic\n    molecular : atomic operator atomic\n    molecular : atomic\n    \n    atomic : ATOMIC\n    \n    lparenthesis : LEFTPARENTHESIS\n    \n    rparenthesis : RIGHTPARENTHESIS\n    '
    
_lr_action_items = {'LEFTPARENTHESIS':([0,3,5,7,8,9,10,11,12,19,],[5,5,-16,5,-2,-3,-4,-5,-6,5,]),'ATOMIC':([0,3,5,7,8,9,10,11,12,15,19,21,],[6,6,-16,6,-2,-3,-4,-5,-6,6,6,6,]),'$end':([1,2,4,6,16,17,18,20,22,26,27,28,],[0,-1,-14,-15,-11,-12,-7,-17,-13,-8,-9,-10,]),'OR':([2,4,6,13,14,16,17,18,20,22,23,24,25,26,27,28,],[8,8,-15,8,8,8,8,-7,-17,-13,8,8,-13,-8,-9,-10,]),'AND':([2,4,6,13,14,16,17,18,20,22,23,24,25,26,27,28,],[9,9,-15,9,9,9,9,-7,-17,-13,9,9,-13,-8,-9,-10,]),'IMPLY':([2,4,6,13,14,16,17,18,20,22,23,24,25,26,27,28,],[10,10,-15,10,10,10,10,-7,-17,-13,10,10,-13,-8,-9,-10,]),'DOUBLEIMPLY':([2,4,6,13,14,16,17,18,20,22,23,24,25,26,27,28,],[11,11,-15,11,11,11,11,-7,-17,-13,11,11,-13,-8,-9,-10,]),'EXCLUSIVEOR':([2,4,6,13,14,16,17,18,20,22,23,24,25,26,27,28,],[12,12,-15,12,12,12,12,-7,-17,-13,12,12,-13,-8,-9,-10,]),'RIGHTPARENTHESIS':([6,13,14,16,17,18,20,22,23,24,25,26,27,28,],[-15,20,-14,-11,-12,-7,-17,-13,20,20,20,-8,-9,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'mainStructure':([0,],[1,]),'molecular':([0,3,7,19,],[2,13,16,23,]),'lparenthesis':([0,3,7,19,],[3,3,3,3,]),'atomic':([0,3,7,15,19,21,],[4,14,17,22,24,25,]),'operator':([2,4,13,14,16,17,23,24,],[7,15,19,21,7,15,7,15,]),'rparenthesis':([13,23,24,25,],[18,26,27,28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> mainStructure","S'",1,None,None,None),
  ('mainStructure -> molecular','mainStructure',1,'p_mainStructure','SyntacticAnalyzer.py',12),
  ('operator -> OR','operator',1,'p_operator','SyntacticAnalyzer.py',18),
  ('operator -> AND','operator',1,'p_operator','SyntacticAnalyzer.py',19),
  ('operator -> IMPLY','operator',1,'p_operator','SyntacticAnalyzer.py',20),
  ('operator -> DOUBLEIMPLY','operator',1,'p_operator','SyntacticAnalyzer.py',21),
  ('operator -> EXCLUSIVEOR','operator',1,'p_operator','SyntacticAnalyzer.py',22),
  ('molecular -> lparenthesis molecular rparenthesis','molecular',3,'p_molecular','SyntacticAnalyzer.py',30),
  ('molecular -> lparenthesis molecular operator molecular rparenthesis','molecular',5,'p_molecular','SyntacticAnalyzer.py',31),
  ('molecular -> lparenthesis molecular operator atomic rparenthesis','molecular',5,'p_molecular','SyntacticAnalyzer.py',32),
  ('molecular -> lparenthesis atomic operator atomic rparenthesis','molecular',5,'p_molecular','SyntacticAnalyzer.py',33),
  ('molecular -> molecular operator molecular','molecular',3,'p_molecular','SyntacticAnalyzer.py',34),
  ('molecular -> molecular operator atomic','molecular',3,'p_molecular','SyntacticAnalyzer.py',35),
  ('molecular -> atomic operator atomic','molecular',3,'p_molecular','SyntacticAnalyzer.py',36),
  ('molecular -> atomic','molecular',1,'p_molecular','SyntacticAnalyzer.py',37),
  ('atomic -> ATOMIC','atomic',1,'p_atomic','SyntacticAnalyzer.py',47),
  ('lparenthesis -> LEFTPARENTHESIS','lparenthesis',1,'p_lparenthesis','SyntacticAnalyzer.py',54),
  ('rparenthesis -> RIGHTPARENTHESIS','rparenthesis',1,'p_rparenthesis','SyntacticAnalyzer.py',59),
]
